//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimVanSorunBildirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvuru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basvuru()
        {
            this.Cevaplar = new HashSet<Cevaplar>();
            this.Dokumanlar = new HashSet<Dokumanlar>();
            this.Kanit = new HashSet<Kanit>();
            this.Sevk = new HashSet<Sevk>();
        }
    
        public int basvuru_id { get; set; }
        public string konum { get; set; }
        public Nullable<System.DateTime> basvuru_zamani { get; set; }
        public string basvuru_durumu { get; set; }
        public string dogrulanan_kisi { get; set; }
        public Nullable<int> sorun_turu_id { get; set; }
        public Nullable<int> kurum_id { get; set; }
        public Nullable<int> yetkili_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual Sorun_turu Sorun_turu { get; set; }
        public virtual Kurum Kurum { get; set; }
        public virtual Yetkililer Yetkililer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cevaplar> Cevaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokumanlar> Dokumanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kanit> Kanit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sevk> Sevk { get; set; }
    }
}
