//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimVanSorunBildirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cevaplar
    {
        public int cevap_id { get; set; }
        public Nullable<System.DateTime> cevap_zamani { get; set; }
        public string cevap_metni { get; set; }
        public Nullable<int> basvuru_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual Basvuru Basvuru { get; set; }
    }
}
