//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimVanSorunBildirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int log_id { get; set; }
        public string tablo_adi { get; set; }
        public Nullable<System.DateTime> degisim_zamani { get; set; }
        public string ip_adresi { get; set; }
        public Nullable<int> kullanıcı_id { get; set; }
        public string log_detay { get; set; }
        public bool is_active { get; set; }
    }
}
