//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimVanSorunBildirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sevk
    {
        public int sevk_id { get; set; }
        public Nullable<System.DateTime> sevk_zamani { get; set; }
        public Nullable<int> basvuru_id { get; set; }
        public Nullable<int> birim_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual Basvuru Basvuru { get; set; }
        public virtual Birim Birim { get; set; }
    }
}
